[auth]
# Activer l'authentification par email
enable_email_signup = true
enable_email_confirmations = false
enable_email_signin = true
mailer_autoconfirm = true
mailer_otp_exp = 3600
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000", "https://your-production-url.com"]

[auth.email]
enable_signup = true
double_confirm_changes = false
enable_confirmations = false

[auth.external.google]
enabled = false
client_id = ""
secret = ""

[auth.external.github]
enabled = false
client_id = ""
secret = ""